# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'aqua-alpine'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'aquaken'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
- task: Bash@3
  inputs:
    filePath: 'scan-new-image.sh'
    arguments: 'http://34.75.241.250:8080 ACR aqua-alpine:$(Build.BuildId)'
  displayName: 'Scan an image using the Aqua API.'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      which jq